### PR TITLE
Added ability to test all js files within a folder and all its subfolders

### PR DESCRIPTION
**Pull request by swelshh**
Hey Sebastien,

Thanks so much for this module, it is awesome!  I wanted to be able to run tests on all the js files in a folder and all its subfolders.

Not sure I did this in the way you would want, so if you don't want to merge my changes I will completely understand.  Or if you would like me to make changes on my end before merging I'd be happy to, just let me know.

Thanks,
Welsh

### CODE REVIEW

**Comment by swelshh** [comment]
Hey, forgot to update for the web call.  I just did another commit on my repo, but don't know how to update the pull request.  Sorry about that, if you decide to merge the first changes I can prob do another pull request.

**Comment by SebCourvoisier4D** [comment]
Hi Welsh,

Thanks, I'll have a look at this today. 

We're still discussing the actual plan about this module and its related components (the widget and the extension), because the QA team would like to ship them with the product (Server and Studio), so there would be no need to install them separately. As a consequence, I still don't know if it will remain in Github or be moved to our private repository (or maintained in both repositories).

I also made some big changes to the module this weekend (offline...) in order to make it compatible with our current testing framework, so there's a huge merging task ahead for me anyway :)

Cheers

**Comment by swelshh** [comment]
Gotcha, makes sense, what you've built here is really awesome.  My use case for recursive folders...

If I had a project with these files
Model/MyClass1/MyClass1.js
Model/MyClass2/MyClass2.js
Model/MyClass3/MyClass3.js
Modules/myModule1/index.js
Modules/anotherModule.js

I would add the following files to do my testing.  So I would basically mirror my project in the Test folder:
Test/Model/MyClass1/MyClass1.js
Test/Model/MyClass2/MyClass2.js
Test/Model/MyClass3/MyClass3.js
Test/Modules/myModule1/index.js
Test/Modules/anotherModule.js

With the recursive support, I can just point to my Test/ folder and have it test everything.  Fun stuff!  Started using this in my projects already.  Thanks again, really great module.

Welsh

**Comment by SebCourvoisier4D** [comment]
Thanks ^^

It's great to have the recursive support too!

Please note that the naming scheme could change a little as I plan to merge this new module with the old one we already use (simply named "unitTest"). It's being decided (that's why we haven't publicly talk about that stuff yet).

We also plan to add some nice features to the [add-on](https://github.com/SebCourvoisier4D/waktest-addon), like a generator of test suite skeletons for the DataStore Model, Modules, etc.

**Pull request merged**
